driver: mysql # 连接驱动
host: localhost # ip地址
port: 3306 # 端口
database: bbs # 数据库
username: env(MYSQL_USERNAME) # 用户名
password: env(MYSQL_PASSWORD) # 密码
charset: utf8mb4 # 字符集
collation: utf8mb4_unicode_ci # 字符序
timeout: 10s # 连接超时
read_timeout: 2s # 读超时
write_timeout: 2s # 写超时
parse_time: true # 是否解析时间
protocol: tcp # 传输协议
loc: Local # 时区
conn_max_idle: 10 # 连接池最大空闲连接数
conn_max_open: 20 # 连接池最大连接数
conn_max_lifetime: 1h # 连接数最大生命周期
